language: php
php:
  - 7.0
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
    repo: Barvoj/workshop-duben
after_success:
  - chmod 600 id_rsa
  - mv id_dsa ~/.ssh/id_dsa
before_install:
  - openssl aes-256-cbc -K $encrypted_8d58c687386a_key -iv $encrypted_8d58c687386a_iv -in id_dsa.enc -out id_dsa -d
